### ISSUE TITLE
Plugin crashes

### ISSUE THREAD

**Issue by abutizi** [jepiqueau/capacitor-video-player#47] opened 2021-07-17 12:02 UTC
Thank you for this plugin, however, it always crashes with this error.
I just cannot figure out what is wrong? I've spent 2 days with it and I'm running out of idea.

I'm only running it on Android.

This is the error I'm getting from logcat whenever I call the initPlayer

  2021-07-17 13:51:34.574 2488-4658/io.socialvibes.app E/Capacitor: Serious error executing plugin
      java.lang.reflect.InvocationTargetException
          at java.lang.reflect.Method.invoke(Native Method)
          at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:99)
          at com.getcapacitor.Bridge$1.run(Bridge.java:542)
          at android.os.Handler.handleCallback(Handler.java:938)
          at android.os.Handler.dispatchMessage(Handler.java:99)
          at android.os.Looper.loop(Looper.java:246)
          at android.os.HandlerThread.run(HandlerThread.java:67)
       Caused by: java.lang.StringIndexOutOfBoundsException: length=0; index=4
          at java.lang.String.substring(String.java:2060)
          at com.jeep.plugin.capacitor.CapacitorVideoPlayer.getFilePath(CapacitorVideoPlayer.java:163)
          at com.jeep.plugin.capacitor.CapacitorVideoPlayer.initPlayer(CapacitorVideoPlayer.java:134)
          at java.lang.reflect.Method.invoke(Native Method) 
          at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:99) 
          at com.getcapacitor.Bridge$1.run(Bridge.java:542) 
          at android.os.Handler.handleCallback(Handler.java:938) 
          at android.os.Handler.dispatchMessage(Handler.java:99) 
          at android.os.Looper.loop(Looper.java:246) 
          at android.os.HandlerThread.run(HandlerThread.java:67) 
  2021-07-17 13:51:34.575 2488-4658/io.socialvibes.app E/AndroidRuntime: FATAL EXCEPTION: CapacitorPlugins
      Process: io.socialvibes.app, PID: 2488
      java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
          at com.getcapacitor.Bridge$1.run(Bridge.java:551)
          at android.os.Handler.handleCallback(Handler.java:938)
          at android.os.Handler.dispatchMessage(Handler.java:99)
          at android.os.Looper.loop(Looper.java:246)
          at android.os.HandlerThread.run(HandlerThread.java:67)
       Caused by: java.lang.reflect.InvocationTargetException
          at java.lang.reflect.Method.invoke(Native Method)
          at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:99)
          at com.getcapacitor.Bridge$1.run(Bridge.java:542)
          at android.os.Handler.handleCallback(Handler.java:938) 
          at android.os.Handler.dispatchMessage(Handler.java:99) 
          at android.os.Looper.loop(Looper.java:246) 
          at android.os.HandlerThread.run(HandlerThread.java:67) 
       Caused by: java.lang.StringIndexOutOfBoundsException: length=0; index=4
          at java.lang.String.substring(String.java:2060)
          at com.jeep.plugin.capacitor.CapacitorVideoPlayer.getFilePath(CapacitorVideoPlayer.java:163)
          at com.jeep.plugin.capacitor.CapacitorVideoPlayer.initPlayer(CapacitorVideoPlayer.java:134)
          at java.lang.reflect.Method.invoke(Native Method) 
          at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:99) 
          at com.getcapacitor.Bridge$1.run(Bridge.java:542) 
          at android.os.Handler.handleCallback(Handler.java:938) 
          at android.os.Handler.dispatchMessage(Handler.java:99) 
          at android.os.Looper.loop(Looper.java:246) 
          at android.os.HandlerThread.run(HandlerThread.java:67) 

My page ts:

  async ngOnInit() {
         this._videoPlayer = CapacitorVideoPlayer;
    }

  async ionViewDidEnter() {

    var url = 'https://archive.org/download/BigBuckBunny_124/Content/big_buck_bunny_720p_surround.mp4'

    const res: any = await this._videoPlayer.initPlayer({
      mode: "fullscreen", url: url,
      playerId: "fullscreen", componentTag: "app-tab1"
    });      
    
    console.log("res " + JSON.stringify(res));
  
    }

My html:
  
  `´´<ion-content>
   ´´<div id="fullscreen" slot="fixed"></div>
  ´´</ion-content>`

Is there anything I have missed?

**Comment by jepiqueau** [comment] 2021-07-17 19:13
@abutizi Can you share your package.json file and the Main activity java file

**Comment by kochax** [comment] 2021-08-25 07:08
Same problem here.

packages.json

![image](https://user-images.githubusercontent.com/11221552/130742720-295cd453-0449-4469-bb9c-5e824d0fecb2.png)


MainActivity

![image](https://user-images.githubusercontent.com/11221552/130742744-adaea33e-5fb6-4762-90da-b1e23df2b818.png)


Error log:

`2021-08-25 08:49:57.721 30629-30702/at.energy42.energy42 E/Capacitor: Serious error executing plugin
    java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:121)
        at com.getcapacitor.Bridge.lambda$callPluginMethod$0$Bridge(Bridge.java:584)
        at com.getcapacitor.-$$Lambda$Bridge$25SFHybyAQk7zS27hTVXh2p8tmw.run(lambda)
        at android.os.Handler.handleCallback(Handler.java:761)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:156)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: java.lang.StringIndexOutOfBoundsException: length=0; regionStart=0; regionLength=4
        at java.lang.String.substring(String.java:1931)
        at com.jeep.plugin.capacitor.capacitorvideoplayer.Utilities.FilesUtils.getFilePath(FilesUtils.java:16)
        at com.jeep.plugin.capacitor.capacitorvideoplayer.CapacitorVideoPlayerPlugin.initPlayer(CapacitorVideoPlayerPlugin.java:118)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:121) 
        at com.getcapacitor.Bridge.lambda$callPluginMethod$0$Bridge(Bridge.java:584) 
        at com.getcapacitor.-$$Lambda$Bridge$25SFHybyAQk7zS27hTVXh2p8tmw.run(lambda) 
        at android.os.Handler.handleCallback(Handler.java:761) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:156) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
2021-08-25 08:49:57.725 30629-30629/at.energy42.energy42 I/HwSecImmHelper: mSecurityInputMethodService is null
2021-08-25 08:49:57.832 30629-30634/at.energy42.energy42 I/art: Do partial code cache collection, code=26KB, data=30KB
2021-08-25 08:49:57.833 30629-30634/at.energy42.energy42 I/art: After code cache collection, code=22KB, data=27KB
2021-08-25 08:49:57.833 30629-30634/at.energy42.energy42 I/art: Increasing code cache capacity to 128KB
2021-08-25 08:49:57.921 30629-30702/at.energy42.energy42 E/AndroidRuntime: FATAL EXCEPTION: CapacitorPlugins
    Process: at.energy42.energy42, PID: 30629
    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.getcapacitor.Bridge.lambda$callPluginMethod$0$Bridge(Bridge.java:593)
        at com.getcapacitor.-$$Lambda$Bridge$25SFHybyAQk7zS27hTVXh2p8tmw.run(lambda)
        at android.os.Handler.handleCallback(Handler.java:761)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:156)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:121)
        at com.getcapacitor.Bridge.lambda$callPluginMethod$0$Bridge(Bridge.java:584)
        at com.getcapacitor.-$$Lambda$Bridge$25SFHybyAQk7zS27hTVXh2p8tmw.run(lambda) 
        at android.os.Handler.handleCallback(Handler.java:761) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:156) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
     Caused by: java.lang.StringIndexOutOfBoundsException: length=0; regionStart=0; regionLength=4
        at java.lang.String.substring(String.java:1931)
        at com.jeep.plugin.capacitor.capacitorvideoplayer.Utilities.FilesUtils.getFilePath(FilesUtils.java:16)
        at com.jeep.plugin.capacitor.capacitorvideoplayer.CapacitorVideoPlayerPlugin.initPlayer(CapacitorVideoPlayerPlugin.java:118)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:121) 
        at com.getcapacitor.Bridge.lambda$callPluginMethod$0$Bridge(Bridge.java:584) 
        at com.getcapacitor.-$$Lambda$Bridge$25SFHybyAQk7zS27hTVXh2p8tmw.run(lambda) 
        at android.os.Handler.handleCallback(Handler.java:761) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:156) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
`

**Comment by jepiqueau** [comment] 2021-08-30 08:47
@kochax Thanks for reporting this, i was really busy in updating the `@capacitor-community/sqlite` plugin. Did you remove the android folder and redo `npx cap add android` Can you share the code of your app where you call the plugin? i am going to update it to `@capacitor/core@3.2.0` as i could not replicate the crash in the `angular-video-player-app-starter`. Which framework are you using Angular, React or Vue?

**Comment by jepiqueau** [comment] 2021-08-31 06:05
@kochax hi, each time you update to a new release of the plugin you must `sync`. i also as a good practice remove the android folder from the app and add it again with `npx cap add android` to make sure that everything is inline with the `@capacitor/core` and `@capacitor/android`. So i will close the issue. Thanks for using the plugin

**Closed by jepiqueau** 2021-08-31 06:05 UTC
