### ISSUE TITLE
XCODE SIMULATOR > FATAL ERROR WHEN CLOSING APP

### ISSUE THREAD

**Issue by martincres** [jepiqueau/capacitor-video-player#16] opened 2020-06-07 13:07 UTC
Hi, in Xcode when i lunch the application in the simulator and i try to close the application is throwing this error:

Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value: file ..node_modules/capacitor-video-player/ios/Plugin/Plugin.swift, line 37
2020-06-07 10:04:29.200253-0300 App[50972:939203] Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value: file ../node_modules/capacitor-video-player/ios/Plugin/Plugin.swift, line 37.

Do you know what is the reason for this error or how can i solve it?

**Comment by jepiqueau** [comment] 2020-06-08 06:46
@martincres  Thanks for using the plugin, I never got this one so which Xcode version are you running and which simulator are you testing on ?

**Comment by martincres** [comment] 2020-06-08 11:39
Hi @jepiqueau thank you for your answer. 

The problem is in this two observers of the Plugin.swift file

```
        NotificationCenter.default.addObserver(forName: UIApplication.didEnterBackgroundNotification, object: nil, queue: nil) { (notification) in
            self.bgPlayer = self.videoPlayerFullScreenView.videoPlayer.player
            self.videoPlayerFullScreenView.videoPlayer.player = nil
        }

        NotificationCenter.default.addObserver(forName: UIApplication.willEnterForegroundNotification, object: nil, queue: OperationQueue.main) { (notification) in
            self.videoPlayerFullScreenView.videoPlayer.player = self.bgPlayer
        }

```
The workaround that i found its deleting them because im not using them. 

- XCode Version 11.5 (11E608c)
- Simulator Version 11.5 (921.9.1)

The problem also is happening when debugging the application in my phone

**Comment by jepiqueau** [comment] 2020-06-08 13:49
@martincres Can you try this for me as i cannot reproduce the error and i do not have an iphone. When i introduce this new feature (plying in the background i was developing this with the guy who ask for it and he did not have any problem with what we achieved.
moving away this line from the addObserversToNotificationCenter() method
```
self.bgPlayer = self.videoPlayerFullScreenView.videoPlayer.player
```

having this in the addObserversToNotificationCenter() method
```
...
        NotificationCenter.default.addObserver(forName: UIApplication.didEnterBackgroundNotification, object: nil, queue: nil) { (notification) in
            self.videoPlayerFullScreenView.videoPlayer.player = nil
        }

        NotificationCenter.default.addObserver(forName: UIApplication.willEnterForegroundNotification, object: nil, queue: OperationQueue.main) { (notification) in
            self.videoPlayerFullScreenView.videoPlayer.player = self.bgPlayer
        }

```
and adding the line in the initPlayer method like this
```
...
            DispatchQueue.main.async {
                self.videoPlayerFullScreenView = FullScreenVideoPlayerView(videoPath: url,playerId: self.fsPlayerId,exitOnEnd: true)
                self.bgPlayer = self.videoPlayerFullScreenView.videoPlayer.player

                // Present the Player View Controller
                self.bridge.viewController  .present(self.videoPlayerFullScreenView.videoPlayer, animated: true, completion:{
...
```
Tell me if this fix the issue
I use the same Xcode and Simulator releases

**Comment by martincres** [comment] 2020-06-08 14:35
@jepiqueau Of course! I think you have a newer version or development version of the plugin

![image](https://user-images.githubusercontent.com/15253539/84041881-bd953d00-a97a-11ea-9466-6ada3b143d3f.png)

So i leave the initPlayer method like this

```
 DispatchQueue.main.async {
                self.videoPlayerFullScreenView = FullScreenVideoPlayerView(videoPath: url)
                self.bgPlayer = self.videoPlayerFullScreenView.videoPlayer.player

                // Present the Player View Controller
```
But i still having this error in the observers when the APP status changes to INACTIVE:

![image](https://user-images.githubusercontent.com/15253539/84042718-cf2b1480-a97b-11ea-9c54-bddce2886a45.png)

```
APP INACTIVE
Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value: file /Users/martincrespo/Sites/con-prosperidad/con-prosperidad-app/node_modules/capacitor-video-player/ios/Plugin/Plugin.swift, line 37
2020-06-08 11:32:01.452887-0300 App[10024:167875] Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value: file /Users/martincrespo/Sites/con-prosperidad/con-prosperidad-app/node_modules/capacitor-video-player/ios/Plugin/Plugin.swift, line 37
(lldb) 
```

**Comment by jepiqueau** [comment] 2020-06-08 14:41
@martincres  yes i am working on the next release with api method so this is the way i implemented this part and it works fine

**Comment by martincres** [comment] 2020-06-08 14:54
@jepiqueau OK! I can resolve my problem with the workarround mention before.
I suppose that when the release is implemented my issue will be solved.
Do you have any estimated date?

Thank you

**Comment by jepiqueau** [comment] 2020-06-08 16:46
@martincres the web plugin and ios plugin are ready but not published, i am currently working on the Android plugin but it is not as easy as i was using an Intent to open the video player activity from the main activity and i do not know yet how to execute from the main activity a method of the player activity. So hope it will come soon?

**Comment by jepiqueau** [comment] 2020-06-09 05:02
@martincres By the way, thinking back to your problem, i wonder if in Xcode of your project application, you have add the capability for running in background mode which is mandatory.
if not follows these steps:

1. choose your project in the Project Navigator
2. choose the target on the Project Editor
3. choose the Signing & Capabilities tab
4. add the capability for ```Background Modes```
5. select the ```Audio, Airplay, and Picture-in-Picture```option under the list of available modes.

This should solve the issue

**Comment by 7freaks-otte** [comment] 2020-06-09 07:19
This seems to be related to the code we were adding @jepiqueau to support background audio and airplay. I'm sorry that I haven't got back to you until now. I have some improvements regarding the play/pause controls on the lock screen and should really take some time to help you with this.

If I find some time this week, I could as well add a background mode detection to avoid this error if background playback is not desired.

**Comment by martincres** [comment] 2020-06-09 13:52
> @martincres By the way, thinking back to your problem, i wonder if in Xcode of your project application, you have add the capability for running in background mode which is mandatory.
> if not follows these steps:
> 
> 1. choose your project in the Project Navigator
> 2. choose the target on the Project Editor
> 3. choose the Signing & Capabilities tab
> 4. add the capability for `Background Modes`
> 5. select the `Audio, Airplay, and Picture-in-Picture`option under the list of available modes.
> 
> This should solve the issue

No luck with this!

**Comment by jepiqueau** [comment] 2020-06-16 11:57
@martincres  @7freaks-otte A new release 2.1.0 integrating the support for interactive apis for the two natives players is now available. It has required a complete rewrite of the player especially for the android one. Can you tell me if you have still the issue

**Comment by jepiqueau** [comment] 2020-07-18 08:29
@martincres Have you still the issue or did the 2.1.0 release fix the issue

**Comment by eamador** [comment] 2020-07-29 10:10
hi @jepiqueau i am using `2.1.0` and i am having this issue

**Comment by jepiqueau** [comment] 2020-08-05 11:48
@eamador Can you share your app or a replicate to github so i can directly work from there to identify the cause of the bug as i could not replicate it from my own set-up.

**Comment by jepiqueau** [comment] 2020-08-20 17:04
@martincres, @7freaks-otte, @eamador i got a new release **capacitor-video-player 2.3.0-beta.4** Can you tell me if the problem persists. Without comment from your site i will close this issue.

**Closed** 2020-08-24 17:43 UTC
