### ISSUE TITLE
Error on plat iOS

### ISSUE THREAD

**Issue by KANekT** [jepiqueau/capacitor-video-player#72] opened 2022-01-29 09:47 UTC
⚡️  [log] - isLoading
⚡️  To Native ->  Keyboard hide 41095673
⚡️  TO JS undefined
⚡️  To Native ->  Filesystem checkPermissions 41095674
⚡️  [log] - {}
⚡️  TO JS {"publicStorage":"granted"}
⚡️  To Native ->  Filesystem writeFile 41095675
2022-01-29 12:45:14.899049+0300 App[11840:949348] nil host used in call to allowsSpecificHTTPSCertificateForHost
2022-01-29 12:45:14.899137+0300 App[11840:949348] nil host used in call to allowsAnyHTTPSCertificateForHost:
⚡️  TO JS {"uri":"file:\/\/\/var\/mobile\/Containers\/Data\/Application\/DD2537A8-EFD4-42E1-A251-6180238DE075\/Documents\/abd47ff029864187be261fb9e303811e"}
⚡️  To Native ->  Storage set 41095676
⚡️  To Native ->  CapacitorVideoPlayer initPlayer 41095677
⚡️  TO JS undefined
2022-01-29 12:45:15.171634+0300 App[11840:949209] <CATransformLayer: 0x282058b00> - changing property masksToBounds in transform-only layer, will have no effect
2022-01-29 12:45:15.171872+0300 App[11840:949209] <CATransformLayer: 0x282043920> - changing property masksToBounds in transform-only layer, will have no effect
2022-01-29 12:45:15.233243+0300 App[11840:949209] <CATransformLayer: 0x2820540a0> - changing property masksToBounds in transform-only layer, will have no effect
2022-01-29 12:45:15.241375+0300 App[11840:949209] <CATransformLayer: 0x282052be0> - changing property masksToBounds in transform-only layer, will have no effect
2022-01-29 12:45:15.243171+0300 App[11840:949209] <CATransformLayer: 0x28204f920> - changing property masksToBounds in transform-only layer, will have no effect
2022-01-29 12:45:15.264551+0300 App[11840:949209] <CATransformLayer: 0x2820540a0> - changing property allowsGroupBlending in transform-only layer, will have no effect
2022-01-29 12:45:15.264621+0300 App[11840:949209] <CATransformLayer: 0x282052be0> - changing property allowsGroupBlending in transform-only layer, will have no effect
failing to load
Unable to activate audio session:  The operation couldn’t be completed. (OSStatus error 2003329396.)
[Capacitor Plugin Error] - CapacitorVideoPlayer - initPlayer - Unable to serialize plugin response as JSON.Ensure that all data passed to success callback from module method is JSON serializable!
⚡️  TO JS {}
⚡️  [log] - res {"result":false,"method":"initPlayer","message":"initPlayer failed"}

**Comment by jepiqueau** [comment] 2022-01-30 15:12
@KANekT Can you share your app or a simplest repro app so i can figure out what is wrong

**Comment by jepiqueau** [comment] 2022-01-30 15:25
@KANekT if i look at 
```
⚡️ TO JS {"uri":"file:///var/mobile/Containers/Data/Application/DD2537A8-EFD4-42E1-A251-6180238DE075/Documents/abd47ff029864187be261fb9e303811e"}
```
there is `uri` instead of `url`
i also assume `abd47ff029864187be261fb9e303811e` is the name of your video but i do not see any file extension giving the video type

**Comment by KANekT** [comment] 2022-01-31 07:49
i load file from api as Blob

and save to local 

const savedFile = await Filesystem.writeFile({
      path: name,
      data: base64Data,
      directory: Directory.Data,
    });

in player i use savedFile.uri

it work in android and not working in iOS

**Comment by jepiqueau** [comment] 2022-01-31 08:16
@KANekT can you share a small app reproducing the issue. It will help me

**Comment by KANekT** [comment] 2022-01-31 08:32
small app - later

if i use name with ext - iOS worked.

**Comment by jepiqueau** [comment] 2022-01-31 08:36
@KANekT  you try reading Base64 video which is not implemented feature. It is nice to know that it works in Android with the code as is. Seems that to work with iOS i must convert the blob response to URL  to play it with AVplayer

**Comment by jepiqueau** [comment] 2022-01-31 08:38
@KANekT yes the extension is important to définition the type of video

**Comment by KANekT** [comment] 2022-01-31 08:54
> @KANekT yes the extension is important to définition the type of video

oк, for Android extension is not important :)

**Comment by jepiqueau** [comment] 2022-01-31 09:18
@KANekT I will revisit to try understanding and solve it. If you provide me the small app it will help me reproducing and  testing. Thanks anyhow for your contribution to help making a better product

**Comment by jepiqueau** [comment] 2022-01-31 10:30
@KANekT Did you get your base64 video string starting with `data:video/mp4;base64,` or not?

**Comment by KANekT** [comment] 2022-01-31 10:52
> 



> @KANekT Did you get your base64 video string starting with `data:video/mp4;base64,` or not?

is not base64 string - i make test app later in week

**Comment by jepiqueau** [comment] 2022-01-31 11:35
@KANekT Is your Blob got a type ie if i use this function to convert a base64 video to Blob
```
function b64toBlob(dataURI) {
    
    var byteString = atob(dataURI.split(',')[1]);
    var ab = new ArrayBuffer(byteString.length);
    var ia = new Uint8Array(ab);
    
    for (var i = 0; i < byteString.length; i++) {
        ia[i] = byteString.charCodeAt(i);
    }
    return new Blob([ab], { type: 'video/mp4 });
}
```
will this be similar to your response

**Comment by jepiqueau** [comment] 2022-02-02 06:50
@KANekT For iOS when you save it to local you must specify a video type extension.

**Comment by KANekT** [comment] 2022-02-02 08:25
https://github.com/jepiqueau/capacitor-video-player/blob/4c48fe7d5d1757561b9c6b938d68654f6aa3bb96/src/web.ts#L55

may be add check ext in js ?

```
function getExtension(nameFile: string): string | undefined {
  const re = /(?:\.([^.]+))?$/;

  const exec = re.exec(nameFile);

  if (exec !== null) return exec[1];

  return undefined;
}
```

**Comment by jepiqueau** [comment] 2022-02-02 08:55
@KANekT i do not really follow you i thought you were using the iOS plugin part (native) so changing something in the web.ts will not affect the iOS part. On top of this, when it is an https url it works without an extension. It seems the problem is just when it is an internal file.

**Comment by KANekT** [comment] 2022-02-02 09:12
Yes the problem is just when it is an internal file.

**Comment by jepiqueau** [comment] 2022-02-05 09:11
@KANekT Sorry, i have tried a lot of things without success. There is nothing i can do about this, so for iOS you must have a type extension. i will close the issue.

**Closed by jepiqueau** 2022-02-05 09:11 UTC
