### ISSUE TITLE
Exit listener not working correctly on Android

### ISSUE THREAD

**Issue by LucaDaniele99** [jepiqueau/capacitor-video-player#127] opened 2023-05-11 20:03 UTC
Hi everyone,
I'm having a problem with setting up the listeners and make them work on Android.

These are the steps my code execute

1) imports the plugin with `import { CapacitorVideoPlayer } from 'capacitor-video-player';`

2) declares the videoplayer variable: `private videoPlayer: any;`

3) assign CapacitorVideoPlayer to the variable:`this.videoPlayer = CapacitorVideoPlayer;`

4) call `this.videoPlayer.initPlayer({..})`

I have the following code around the initPlayer:

`ScreenOrientation.lock({ type: OrientationType.LANDSCAPE }).then(() =>{
    this.videoPlayer.initPlayer({
        url: ...,
        mode: "fullscreen",
        componentTag: 'vplayer',
        playerId: 'vplayer'
      }).then(() =>{
    this.videoPlayer.addListener("jeepCapVideoPlayerExit").then(()=>{
          this.notification.showToast("exit, "success");
          ScreenOrientation.lock({ type: OrientationType.PORTRAIT }).then(() =>{});
        });
        this.videoPlayer.addListener("jeepCapVideoPlayerEnded").then(()=>{
          this.notification.showToast("end, "success");
          ScreenOrientation.lock({ type: OrientationType.PORTRAIT }).then(() =>{});
        });
  }, err =>{
        console.log(JSON.stringify(err))
      });
  });`

(Sorry can't display formatted,[ here's a copy](https://codeshare.io/K8Ol0P))
The problem is that the exit listener gets called istantly after the player is loaded because I can see the screen go to landscape and then istantly back to portrait. If I remove the autohide time of the toast I see that it has the text "exit" in it so the problem is related to the exit listener.
I hope I explained the problem clearly

Thanks,
Luca

**Comment by PhantomPainX** [comment] 2023-05-11 20:22
Hey, are you using Ionic?

**Comment by LucaDaniele99** [comment] 2023-05-11 20:24
Hi, thanks for the quick reply. Yes I’m using Ionic

Il giorno gio 11 mag 2023 alle 22:22 Manuel García Marín <
***@***.***> ha scritto:

**Comment by PhantomPainX** [comment] 2023-05-11 20:47
Ok, I was facing the same issue long time ago when I tried to lock the screen to landscape before initializing the player. The short answer is that you can't do that from TS, because right after the player initializes, it will revert your screen orientation.

You can lock the screen to landscape in the **FullscreenExoPlayerFragment.java** inside **onCreateView** with this little code:

`getActivity().setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE);`

So this can be your new TS code:

```typescript
this.videoPlayer.initPlayer({
        url: ...,
        mode: "fullscreen",
        playerId: 'vplayer'
}).then(() =>{
        this.videoPlayer.addListener("jeepCapVideoPlayerExit").then(()=>{
            this.notification.showToast("exit, "success");
            ScreenOrientation.lock({ type: OrientationType.PORTRAIT });
        });
        
       this.videoPlayer.addListener("jeepCapVideoPlayerEnded").then(()=>{
            this.notification.showToast("end, "success");
            ScreenOrientation.lock({ type: OrientationType.PORTRAIT });
        });
});
```

Notes:

componentTag is not needed in your case, this says the documentation: Component Tag or DOM Element Tag (React app)

jeepCapVideoPlayerExit will be called when you exit the player somehow and jeepCapVideoPlayerEnded will only be called when the video ends.

The other thing is that I don't know if you are removing the listeners somewhere in your code, it is good practice to do that.

If you have doubts about how to implement the plugin correctly using Ionic, you can check my working code here: https://github.com/PhantomPainX/streaming-ionic/blob/main/src/app/services/video-player/video-player.service.ts

**Comment by LucaDaniele99** [comment] 2023-05-12 09:22
UPDATE:
the new lines in the Java files work, the video goes landscape. The problem is that the end/exit event doesn't get fired so I can't lock the screen back to PORTRAIT.

On iOS there's the same problem I had with iPhone, any solution?

Best regards,
Luca

**Comment by jepiqueau** [comment] 2023-05-12 11:20
@LucaDaniele99 I am pretty surprise that the end/exit event do not fire. Can you elaborate and share your code

**Comment by LucaDaniele99** [comment] 2023-05-12 11:25
Hi, as @PhantomPainX said, if I trigger the rotation lock before doing the
init of the player the exit event is fired as soon as the player is opened.
Adding the line in the .java file the video gets rotated but when I close
the player it doesn’t fire the event (or it’s still fired when I init the
player, I have to check it out)

The code is still the same of the first post apart of the new line in the
.java file

Best regards,
Luca

Il giorno ven 12 mag 2023 alle 13:21 QUEAU Jean Pierre <
***@***.***> ha scritto:

**Comment by PhantomPainX** [comment] 2023-05-12 12:25
As @jepiqueau said, can you share your code to see what is the problem and package.json?

**Comment by PhantomPainX** [comment] 2023-05-12 16:03
Yes, I think the problem can be caused by your capacitor version, because this plugin is not updated yet to cap 5, but I'm not sure though. I don't see problems in the code, are you sure the exit event is fired like you said? Try to check this with a console log.

Try to downgrade your cap version to 4 and test.

**Comment by jepiqueau** [comment] 2023-05-12 16:33
@LucaDaniele99 the plufin has not been upgraded to Capacitor 5 before to do it i need to close as much as i can issues and PRs

**Comment by LucaDaniele99** [comment] 2023-05-13 08:03
Unluckily I can't downgrade to Capacitor 4 as Capacitor will try to install Android 5 version and throw error when building the app so I'll find a workaround.

Just for you interest I may have found the error that cause the event to be fired before the player is closed.
If I log in the console the variable that the .then creates I get:
![Screenshot 2023-05-13 alle 09 59 21](https://github.com/jepiqueau/capacitor-video-player/assets/24780756/5361897b-f236-4d02-9346-b15886e93c33)

If I provide it then I get
![Screenshot 2023-05-13 alle 10 00 37](https://github.com/jepiqueau/capacitor-video-player/assets/24780756/e6895c74-9db9-45e3-baac-81fb12c445ad)

The player still gets open but if I try to get for example the duration providing the playerId it says that no player exists.

Best regards,
Luca

**Comment by jepiqueau** [comment] 2023-05-23 18:48
@LucaDaniele99 @PhantomPainX @kosso release4.8.0 add option displayMode to handle the orientation natively

**Comment by jepiqueau** [comment] 2023-05-23 18:49
@LucaDaniele99 @PhantomPainX @kosso You can test it and close the issue if it works

**Comment by PhantomPainX** [comment] 2023-05-24 19:56
> @LucaDaniele99 @PhantomPainX @kosso release4.8.0 add option displayMode to handle the orientation natively

Hey jepiqueau, first of all thank you for your work. I tested the portrait mode and it works as expected, but using the landscape mode it crashs the application in iOS with the following error: Thread 1: "Supported orientations has no common orientation with the application, and [CapacitorVideoPlayer.LandscapeAVPlayerController shouldAutorotate] is returning YES"

I'd also like to suggest a third option that unlocks the orientation, just like it was before. This option can be left by default or as a third option.

**Comment by jepiqueau** [comment] 2023-05-25 05:27
@PhantomPainX i tested it on an emulator and it was working i do not have a physical iOS device so may be you can try to figure out what the error is. Can you also put in a PR the third option. I you can do it quickly as i would like to release the version 5 quickly

**Comment by jepiqueau** [comment] 2023-05-25 05:52
@PhantomPainX  in Xcode in App General you must set Deployment Info iPhone Orientation to Portrait Landscape Left and Landscape Right on. That will solve the issue

**Comment by jepiqueau** [comment] 2023-05-25 06:47
@PhantomPainX Can you explain me the third option that you are thinking off. What is  ScreenOrientation do we have to import something in TS

**Comment by PhantomPainX** [comment] 2023-05-25 13:35
> @PhantomPainX in Xcode in App General you must set Deployment Info iPhone Orientation to Portrait Landscape Left and Landscape Right on. That will solve the issue

Yes, that solved my issue, it is working now :)

-------

The third option is an unlocked orientation, it is how the plugin worked before, if the user turns his screen, the orientation changes. I already made it creating a controller like you did with Portrait and Landscape mode:

AllOrientationAVPlayerController.swift

```swift
import AVKit
class AllOrientationAVPlayerController: AVPlayerViewController {
    override var supportedInterfaceOrientations: UIInterfaceOrientationMask {
        return .all    }
}
```

I made it to be the default one, if the user doesn't set the portrait or landscape mode then this mode is enabled. if you wan't I can make a PR but I saw you already published the version 5 of this plugin in the master branch, so how can I proceed?

**Comment by jepiqueau** [comment] 2023-05-25 17:15
@PhantomPainX make the PR in 5

**Comment by PhantomPainX** [comment] 2023-05-25 17:56
> @PhantomPainX make the PR in 5

Ok, a few moments ago I added functionality to NowPlayerInfo, basically this:

![descarga](https://github.com/jepiqueau/capacitor-video-player/assets/47803967/8187a9a3-7438-458e-8691-025ef941d963)

So the PR will include that functionality, I am saying this because in the plugin, specifically where the AudioSession is configured, it has the option **mixWithOthers**, which makes the audio of the video mix with other audios, for example if we are playing a video with this plugin and music from Apple Music, then the two audios will be mixed and the NowPlayingInfo notification won't appear, so I took rid of that option.

Can you make a Capacitor 4 version adding these features please?

**Comment by jepiqueau** [comment] 2023-05-30 06:17
@PhantomPainX did you progress on the PR?

**Comment by PhantomPainX** [comment] 2023-06-06 20:00
> @PhantomPainX did you progress on the PR?

Hey sorry, I've been busy these days, the PR is ready #129 

Thanks :)

**Closed** 2023-12-02 10:17 UTC
