### ISSUE TITLE
Play video with url parameters

### ISSUE THREAD

**Issue by tljesse** [jepiqueau/capacitor-video-player#18] opened 2020-08-06 20:24 UTC
It seems that there is an issue if I try to play a video that has any query params it will not load. What I'm trying to do is upload an mp4 to firebase storage, then to access that there is a token attached to the url. When I try to play the video with the token attached it does not load the player.

For instance I have a url that ends like this 

`big_buck_bunny_720p_surround.mp4?alt=media&token=a8abafa7-5fd9-4179-be5f-1963a5b60d51`

When I take off the params then the player will try to load the video but it is rejected without the token attached.

**Comment by jepiqueau** [comment] 2020-08-07 04:42
@tljesse Yes you right, it was not designed to have query params associated with the url. i will have a look to see how to implement it and rely on you for testing

**Comment by jepiqueau** [comment] 2020-08-07 05:10
@tljesse On which platform did you have the issue?

**Comment by jepiqueau** [comment] 2020-08-07 06:07
@tljesse I assume it was on the web platform only this should now be fixed in the beta release
`npm i --save capacitor-video-player@beta` tell me if not or close the issue. Thanks for using the plugin in your contribution in the debugging process

**Comment by tljesse** [comment] 2020-08-07 15:20
Hey @jepiqueau yes I was trying it on the web while running `ionic serve` but I want to be using it on android and ios as well, didn't get around to testing it on either device since it wasn't working on the web. I'll try it out with the beta version

**Comment by jepiqueau** [comment] 2020-08-07 16:46
@tljesse Normally it should work on iOS and Android

**Comment by jepiqueau** [comment] 2020-08-09 08:35
@tljesse Didn't hear from you. Is it working as i would like to move from beta to release

**Comment by jepiqueau** [comment] 2020-08-11 08:50
@tljesse If i do not hear from you today, i will close that issue as for me it is solved

**Comment by tljesse** [comment] 2020-08-11 22:12
Hi @jepiqueau I finally came back around and tried it, there looks to be an error with the url encoding still. With the firebase storage URL they replace `/` with `%2F` or the link won't work.

URL is set as `curriculumVideo%2FBall-AV-5.mp4`
URL is encoded to `curriculumVideo%252FBall-AV-5.mp4`

and this causes the link to break.

**Comment by jepiqueau** [comment] 2020-08-12 08:33
@tljesse Did you try for Android and iOS?

**Comment by tljesse** [comment] 2020-08-17 19:28
Does not appear to work on Android, but will play a normal file without that. On iOS there is also another error appearing when trying to play any video

```
To Native -> CapacitorVideoPlayer isPlaying 110254523
Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value: file /Users/chris/Code/clEAR/amptify-ionic-firebase/node_modules/capacitor-video-player/ios/Plugin/Plugin.swift, line 1092020-08-05 14:23:57.651087-0500 App[886:99004]
```

Looks like this is being thrown at `let isPlaying: Bool = playerView.isPlaying;`

**Comment by jepiqueau** [comment] 2020-08-20 16:59
@tljesse Can you tell me if in the new release **capacitor-video-player 2.3.0-beta.4** the issue is fixed for the web platform? I have tried not to encode the uri . For iOs and Android platform i have no idea how to solve this. Is it something special with firebase storage

**Comment by tljesse** [comment] 2020-08-24 17:25
The beta4 release is working on the web and on Android. For iOS I am getting another error trying to play.

`Failed to set audio session category`

From line 131 of Plugin.swift.

So I [forked](https://github.com/tljesse/capacitor-video-player) and wrapped that section in an if let statement and now it will run on iOS

```
if let isPlaying: Bool = playerView.isPlaying {
  call.success([ "result": true, "method":"isPlaying", "value": isPlaying])
  return
} else {
  print("Caught nil error")
  call.success(["result": false, "method":"isPlaying","value": false])
  return
}
```

I'm not a swift programmer so I don't know if this is any good or not to merge, or if there is something with our environment causing the error in the first place.

**Comment by jepiqueau** [comment] 2020-08-24 18:03
@tljesse
i am pleased that it is now working for the web and android platform.
on iOS can you explained a bit more  
you have  a first issue `Failed to set audio session category`
and a second issue on the isPlaying function
?
 Are you working with the 2.3.0-beta.4
on iOS, you need to set your app Capabilities Background Modes (Audio and AirPlay) in Xcode before compiling

**Comment by tljesse** [comment] 2020-08-24 18:54
Sorry for the confusion, the first issue, audio session I [commented out lines 53-61](https://github.com/tljesse/capacitor-video-player/blob/master/ios/Plugin/Plugin.swift#L53) and solved the issue there. We already have the Audio and AirPlay background modes enabled so I am really unsure why that error is happening.

The second issue on the isPlaying function was with the `Unexpectedly found nil` error which the if let has solved.

**Comment by jepiqueau** [comment] 2020-08-25 04:31
@tljesse I do not really understand the reasons why you get these 2 errors. i did not get them. Are you running on a simulator or on a physical device ? which model and which iOS version?
Do you see these errors when running the `angular-videoplayer-app-starter` app.
the implementation of the audio session is done as `https://developer.apple.com/documentation/avfoundation/avaudiosession` 
Did you call the isPlaying method before receiving the `jeepCapVideoPlayerReady` event fired?

**Comment by tljesse** [comment] 2020-08-25 17:32
I did have the isPlaying outside of the playerReady event since on web the video did not seem to play automatically. I moved that into the event. Maybe that will solve one issue.

These errors only seem to appear when running on device and not on the simulator. I just tried with the starter app and tried to run the test mp4 video on device through xcode, I am still getting audio session category error. I checked to make sure Audio, Airplay and Picture in Picture was set in Background Modes.

```
⚡️  To Native ->  CapacitorVideoPlayer initPlayer 104072712
Failed to set audio session category.
⚡️  TO JS {"method":"initPlayer","message":"Failed to set audio session category.","result":false}
⚡️  [log] - res.result  false
⚡️  [log] - res.message Failed to set audio session category.
```

I'm using the 2nd gen iPhone SE software version 13.6

**Comment by jepiqueau** [comment] 2020-08-25 17:53
@tljesse Thanks for the feedback, i do not have apple device to test  and it works fine on the simulator. for the `isPlaying` it should be in `playerReady` event but i will add your lines in case of for the audio session i do not know what to do except to add a parameter to let the user decide if he wants to set the audio session or not

**Comment by tljesse** [comment] 2020-08-25 18:57
We also ran into another error, this one happened on the simulator and on device. We don't initialize the video player right away it is in a component. When we open the app and then put the app in the background we get this error.

```
APP INACTIVE
Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value: file /Users/amptify/Code/amptify-ionic-firebase/node_modules/capacitor-video-player/ios/Plugin/Plugin.swift, line 109
2020-08-25 12:50:01.556677-0500 App[6220:1804775] Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value: file /Users/amptify/Code/amptify-ionic-firebase/node_modules/capacitor-video-player/ios/Plugin/Plugin.swift, line 109
```

I figured that was the video player not being initialized yet but trying to call it from the background. If I open up the video player before going to the background then go to background this error doesn't occur. I fixed that by adding a check for nil to that line and the next. You can see the [commit here](https://github.com/tljesse/capacitor-video-player/commit/e3f8dbc6c9e444eb8817dfc68b2c6cd75b81a41c).

This error didn't occur in the starter app, I'm guessing the player is initialized in the home screen or somewhere first?

**Comment by jepiqueau** [comment] 2020-08-26 16:43
@tljesse It is a pity that i did not see that before, i update to a new release 2.3.0  which hope solve some of the issues. i will implement it thanks for this

**Closed** 2020-09-09 12:20 UTC
